name: Publish to NPM and GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  # Job 1: Publish to the public NPM registry
  publish-npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js for npmjs.com
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        # This step might fail if the version already exists, but that's okay.
        # The `continue-on-error` flag ensures the workflow doesn't show a big red X.
        continue-on-error: true
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Job 2: Publish to the GitHub Packages registry
  publish-gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permission is required to write to GPR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mgks'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Publish to GitHub Packages
        # This step might also fail if the version exists, which is fine.
        continue-on-error: true
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}